# Permalinks
permalink: pretty

# Setup
url: "https://elitalon.github.io"
baseurl: ""
paginate: 5
timezone: "Europe/Zurich"
feed_url: "https://elitalon.github.io/feed.xml"

# Build settings
exclude: ["public/css/Paratype PT Sans Free Font License.txt"]

# Writing
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

# Default content
title: "Eliezer Tal贸n"
tagline:
description: "I am a Spanish software engineer living in Switzerland. I develop backend and iOS applications mainly, but I dabble in other fields. I like playing guitar, snowboarding, running and swimming. I write here mostly about software development."

# About/contact
author:
  name: "Eliezer Tal贸n"
  url: "https://elitalon.github.io"
  email: ""
social_media:
  mastodon: "https://mastodon.social/@elitalon"
  linkedin: "https://www.linkedin.com/in/elitalon"

# SEO
social:
  name: "Eliezer Tal贸n"
  links:
    - https://mastodon.social/@elitalon
    - https://www.linkedin.com/in/elitalon
    - https://github.com/elitalon

# License
license:
  source: "https://github.com/elitalon/elitalon.github.io"
  url: "http://creativecommons.org/licenses/by/4.0/"
  title: "Creative Commons Attribution 4.0"

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      description: "Eliezer Tal贸n"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      published: true

web_fonts:
  - ptsans_bold_macroman
  - ptsans_bolditalic_macroman
  - ptsans_italic_macroman
  - ptsans_regular_macroman
  - ptsanscaption_bold_macroman
  - ptsanscaption_regular_macroman
  - ptsansnarrow_bold_macroman
  - ptsansnarrow_regular_macroman
  - ptserif_bold_macroman
  - ptserif_bolditalic_macroman
  - ptserif_italic_macroman
  - ptserif_regular_macroman
  - ptserifcaption_italic_macroman
  - ptserifcaption_regular_macroman
